// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/20/2026, 1:54:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/kk/Documents/poems/poems/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/plugins/**/*.{js,ts,mjs}","C:/Users/kk/Documents/poems/poems/composables/**/*.{js,ts,mjs}","C:/Users/kk/Documents/poems/poems/utils/**/*.{js,ts,mjs}","C:/Users/kk/Documents/poems/poems/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kk/Documents/poems/poems/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;